### ISSUE TITLE
Doesn't link on windows

### ISSUE THREAD

**Issue by kdalbey** [LANL-Seismoacoustics/e1#1]
running anaconda with python 3.7 on windows and pisces 0.3.2 I was getting
`LINK : error LNK2001: unresolved external symbol PyInit__libe1`
when I tried to `pip install e1=0.1.0` (i think)

the reason I moved to pisces 0.3.2 from an earlier version was I was previously getting a  
 ` LINK : error LNK2001: unresolved external symbol PyInit__libecompression` which is the same problem prior to e_compression being moved into e1 (and moving it out of pisces and making it optional is what allowed me to pip install pisces 0.3.2)

the problem that was causing that issue is documented here https://stackoverflow.com/questions/34689210/error-exporting-symbol-when-building-python-c-extension-in-windows
basically for python 2.7  line 75 of ecompression.c
`void initlibecompression(){}`
was fine but in python 3.5+ you would need to do a 
`void PyInit_libecompression() {}`

but that doesn't work because e_compression became a subpackage of e1 and according to https://docs.python.org/3/distutils/setupscript.html#extension-names-and-packages
than means line 30 of setup.py needs to change to something like
`ext_modules=[Extension('_libe1.e_compression', ['src/e_compression.c'])]`,
which means line 75 of ecompression.c needs to change to something like
like `void PyInit_e_compression(){}`

that links and lets e1 pip install but then
when line 16 of pisces' readwaveform.py tries to 
`from e1 import e_compression`
it dies and even changing line 12 of e1.py to 
`libecomp = C.CDLL(os.path.dirname(__file__) + os.path.sep + '_libe1.e_compression' + ext)`
doesn't help.  I admit to be shooting in the dark at this point, and maybe that .e_compression addition on line 12 of e1.py made things worse.

Help please :D and thank you.

**Comment by jkmacc-LANL** [comment]
Thanks for this, @kdalbey.  Since I'm not a windows guy, I think I will try to make a PR that adds GitHub Actions to this repo, so that we can run CI tests on a Windows box.  Docs for how to do this aren't exactly easy to find ATM, but I'll keep at it.

**Comment by jkmacc-LANL** [comment]
I think I've successfully gotten the Windows CI working in GH Actions, and [this](https://github.com/LANL-Seismoacoustics/e1/runs/1145632382?check_suite_focus=true#step:5:31) looks like the one you're getting.  At least it's a place for me to start digging into it.  Thanks for your patience.

**Comment by jkmacc-LANL** [comment]
@kdalbey Do you need Python 3.5 to work?  It's deprecated.

**Comment by kdalbey** [comment]
I'm using python 3.7.3  I don't need 3.5

**Comment by jkmacc-LANL** [comment]
@kdalbey I've made a PR #2 for this, but it could use your input (it's still not working).  Many thanks.

EDIT: fixed PR link
